### ISSUE TITLE
感謝更新

### ISSUE THREAD

**Issue by jimmy123j** [addie-tyc/shopee-coins-collector#7]
你好，這幾天突然開始失敗，Follow 你的更新修改後已正常，持續觀察
感謝大大接手更新

**Comment by addie-tyc** [comment]
@jimmy123j 安安，抱歉我現在才看到 > <，前陣子有注意到 fail 但 4/19 才有空處理 XD
失敗原因是蝦皮更新了定位 button 用的 wording 導致瀏覽器等不到目標元件所以 timeout，所以更新文字後就正常了～

**Comment by jimmy123j** [comment]
謝謝大大更新，大大好人，上廁所都有衛生紙
另外，希望有機會可以加入蝦皮這個點寶箱的活動，每天點一下至少可以 +0.01
[https://imgur.com/BskOPuI](url)
