### ISSUE TITLE
自動化程式簽到失敗

### ISSUE THREAD

**Issue by boss913** [addie-tyc/shopee-coins-collector#8]
最近自動跑action都會失敗
手動自己去蝦皮也無法領，但不用的那天可以手動領取蝦幣

**Comment by addie-tyc** [comment]
謝謝提醒，不過我剛剛也無法手動領，還無法排解 > <

**Comment by addie-tyc** [comment]
根據原作者的 [issue #53](https://github.com/wdzeng/shopee-coins-bot/issues/53)，原因是蝦皮開始擋機器人，
因為本 repo 改寫後使用的套件不同，目前在著手修復！

**Comment by wdzeng** [comment]
用 action 會被 ban，大家小心 👀👀

**Comment by addie-tyc** [comment]
@wdzeng 大神安安，在修復的過程有些問題想請教～

我按照大神們提及的解法嘗試修復，在 local 測試還是會被偵測而無法領取 > <
```javascript
await page.evaluateOnNewDocument(() => {
  Object.defineProperty(navigator, 'webdriver', {
    get: () => undefined
  });
});
```

後來根據[這篇](https://stackoverflow.com/questions/56335066/changing-window-navigator-within-puppeteer-to-bypass-antibot-system)提到的問題改寫成下面的樣子（雖然會報 deprecated XD），有通過[測試](https://intoli.com/blog/not-possible-to-block-chrome-headless/chrome-headless-test.html)，但還是沒辦法成功簽到
```javascript
delete navigator.__proto__.webdriver;
```

還有什麼可能的原因嗎？QwQ

**Comment by wdzeng** [comment]
> @wdzeng 大神安安，在修復的過程有些問題想請教～
> 
> 我按照大神們提及的解法嘗試修復，在 local 測試還是會被偵測而無法領取 > <
> 
> ```js
> await page.evaluateOnNewDocument(() => {
>   Object.defineProperty(navigator, 'webdriver', {
>     get: () => undefined
>   });
> });
> ```
> 
> 後來根據[這篇](https://stackoverflow.com/questions/56335066/changing-window-navigator-within-puppeteer-to-bypass-antibot-system)提到的問題改寫成下面的樣子（雖然會報 deprecated XD），有通過[測試](https://intoli.com/blog/not-possible-to-block-chrome-headless/chrome-headless-test.html)，但還是沒辦法成功簽到
> 
> ```js
> delete navigator.__proto__.webdriver;
> ```
> 
> 還有什麼可能的原因嗎？QwQ

避偵測的 commit 在[這裡](https://github.com/wdzeng/shopee-coins-bot/commit/026da4643f6bdbb92cd4c05eec8c5e207198acf5)。這裡面包含三個改善方法：

- 移除 `navigator.webdriver` 的 page onload script
- 新增 `--disable-blink-features` 等 option，但我不清楚這些 option 具體的意思
- 把 `cdc_xxxx` 改成其他等長的字串

除此之外我也不知道還有哪些地方可以改進ㄌQQ

**Comment by addie-tyc** [comment]
@wdzeng 感謝大大的分享！很抱歉近來沒有關注這個 repo 沒有即時注意到，這個週末會嘗試修正看看 🙇

**Comment by addie-tyc** [comment]
目前地端測試已經通過，但只有一個帳號，Action 的部分只能明天再試 QwQb

**Comment by addie-tyc** [comment]
如同大神描述，用 GitHub Actions 可能因為 IP 等因素會被 ban，只能用 self-hosted 的機器或是 docker 來處理了 QwQ
