### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by haiheo963** [addie-tyc/shopee-coins-collector#9]
What is AES_KEY?

**Comment by addie-tyc** [comment]
It's the secret key used to encrypt you cookie in GitHub Actions cache.
You can check [wiki](https://en.wikipedia.org/wiki/Advanced_Encryption_Standard) for more information.

**Comment by haiheo963** [comment]
ok tks but how to find thay key:?

**Comment by addie-tyc** [comment]
You can just generate one by yourself and keep it carefully.
